name: neuralsfm
channels:
  - https://dx-mirrors.sensetime.com/anaconda/cloud/pytorch
  # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.8.0
  - torchvision=0.9.1
  - cudatoolkit=10.2   #10.1 for cluster sh1988, 10.2 for other clusters
  - ipython
  - tqdm
  - matplotlib
  - pylint
  - conda-forge::jupyterlab
  # - conda-forge::pytorch-lightning=1.6
  - conda-forge::h5py=3.1.0
  - conda-forge::loguru=0.5.3
  - conda-forge::scipy
  - conda-forge::numba
  - conda-forge::ipdb
  - conda-forge::albumentations=0.5.1
  # Sensetime Petrel OSS SDK2.0 (petrel-oss-sdk-v2.0.4-10-ga9f0775)
  # be sure to use their compiled boost, install memcache yourself is okay
  - pip
  - pip:
    - -r requirements.txt
