# @package _global_

type: merge_anno
task_name: gats_loftr
match_type: 'softmax'
split: 'val'

data_base_dir: '/raid/zihao/arscan_aligned_temp/arscan_data'
sfm_dir: '/raid/hexingyi/onepose_sfm_v3'
merge_output_dir: '/raid/hexingyi/onepose_merged'

names:
    - '0408'
    - '0409'
    - '0419'
    - '0422'
    - '0423'
    - '0424'
    - '0447'
    - '0450'
    - '0452'
    - '0455'
    - '0456'
    - '0458'
    - '0459'
    - '0466'
    - '0468'
    - '0469'
    - '0470'
    - '0471'
    - '0472'
    - '0473'
    - '0474'
    - '0476'
    - '0480'
    - '0483'
    - '0486'
    - '0487'
    - '0488'
    - '0489'
    - '0490'
    - '0492'
    - '0493'
    - '0494'
    - '0495'
    - '0496'
    - '0497'
    - '0498'
    - '0500'
    - '0501'
    - '0502'
    - '0503'
    - '0504'
    - '0508'
    - '0510'
    - '0511'
    - '0517'
    - '0518'
    - '0519'
    - '0520'
    - '0521'
    - '0522'
    - '0523'
    - '0525'
    - '0526'
    - '0527'
    - '0534'
    - '0535'
    - '0537'
    - '0539'
    - '0543'
    - '0547'
    - '0548'
    - '0550'
    - '0551'
    - '0552'
    - '0557'
    - '0558'
    - '0559'
    - '0560'
    - '0564'
    - '0565'
    - '0568'
    - '0570'
    - '0576'
    - '0577'
    - '0578'
    - '0579'
    - '0580'
    - '0582'
    - '0583'
    - '0593'
    - '0594'
    - '0595'

    # # Val Set
    # - '0514'
    # - '0515'
    # - '0586'
    # - '0587'
    # - '0588'
    # - '0589'
    # - '0590'
    # - '0591'

    # # Hard case:
    # - '0601'
    # - '0603'
    # - '0604'
    # - '0605'


# names: ${data_base_dir}
# exception_obj_names: 
#     -
# top_k_obj: null

val_use_last_n_seq: 1


network:
    detection: loftr
    matching: loftr

datamodule:
    data_dir: ${data_base_dir}
    sfm_dir: ${sfm_dir}

    out_path: ${merge_output_dir}/${task_name}/${split}.json


hydra:
    run:
        dir: ${work_dir}