# @package _global_

type: merge_anno
task_name: gats_loftr
match_type: 'softmax'
split: 'val'

# data_base_dir: '/nas/users/hexingyi/arscan_data_val'
data_base_dir: '/nas/users/hexingyi/arscan_data'
sfm_dir: '/nas/users/hexingyi/onepose_sfm_v3'
merge_output_dir: '/nas/users/hexingyi/onepose_merged'

names:
    # val set
    # - '0408'
    - '0618'
    - '0616'
    # - '0456'
    # - '0499'
    # - '0506'
    # - '0507'
    # - '0509'

# Another method
# names: ${data_base_dir}
# exception_obj_names: 
#     -
# top_k_obj: null
val_use_last_n_seq: 2

network:
    detection: loftr
    matching: loftr

datamodule:
    data_dir: ${data_base_dir}
    sfm_dir: ${sfm_dir}

    out_path: ${merge_output_dir}/${task_name}/${split}.json


hydra:
    run:
        dir: ${work_dir}