# @package _global_

type: sfm
work_dir: ${hydra:runtime.cwd}
data_base_dir: "/cephfs-mvs/3dv-research/hexingyi/scannet_onposeform"
# data_base_dir: '/nas/users/hexingyi/onepose_hard_data'
output_base_dir: "/cephfs-mvs/3dv-research/hexingyi/scannet_sfm"
match_type: "softmax"
redo: True
enable_loftr_post_refine: True

overwrite_all: True
overwrite_coarse: True
overwrite_fine: True

use_global_ray: False
use_local_ray: True
debug: True

ray:
  slurm: False
  n_workers: 2
  n_cpus_per_worker: 5
  n_gpus_per_worker: 1
  local_mode: False
dataset:
  max_num_kp3d: 50000 # 20000 original
  max_num_kp2d: 10000

  # data_dir:
  #     # - ${data_base_dir}/0410-huiyuan-box huiyuan-1 huiyuan-2
  #     - ${data_base_dir}/0413-juliecookies-box juliecookies-1 juliecookies-2
  #     - ${data_base_dir}/0414-babydiapers-others babydiapers-1 babydiapers-2
  #     - ${data_base_dir}/0415-captaincup-others captaincup-1 captaincup-2
  #     - ${data_base_dir}/0416-tongyinoodles-others tongyinoodles-1 tongyinoodles-2
  #     - ${data_base_dir}/0418-cookies1-others cookies1-1 cookies1-2
  #     - ${data_base_dir}/0420-liuliumei-others liuliumei-1 liuliumei-2
  #     - ${data_base_dir}/0421-cannedfish-others cannedfish-1 cannedfish-2
  #     - ${data_base_dir}/0443-wheatbear-others wheatbear-1 wheatbear-2
  #     - ${data_base_dir}/0445-pistonhead-others pistonhead-1 pistonhead-2

  #     # - ${data_base_dir}/0548-duck-others duck-1
  #     # - ${data_base_dir}/0477-cutlet-bottle cutlet-1
  #     # - ${data_base_dir}/0600-toyrobot-others toyrobot-1
  #     # - ${data_base_dir}/0601-oldtea-box oldtea-1
  #     # - ${data_base_dir}/0602-sensesheep-others sensesheep-1
  #     # - ${data_base_dir}/0603-fakebanana-others fakebanana-1
  #     # - ${data_base_dir}/0604-catmodel-others catmodel-1
  #     # - ${data_base_dir}/0605-pingpangball-ball pingpangball-1
  #     # - ${data_base_dir}/0606-yellowduck-others yellowduck-1
  #     # - ${data_base_dir}/0607-oringe-others oringe-1
  #     # - ${data_base_dir}/0608-greenteapot-others greenteapot-1
  #     # - ${data_base_dir}/0609-blackteapot-others blackteapot-1
  #     - ${data_base_dir}/0610-lecreusetcup-others lecreusetcup-1
  #     # - ${data_base_dir}/0611-bosecolumnaudio-others bosecolumnaudio-1

  data_dir: ${data_base_dir}
  top_k_obj: null
  num_seq: null
  ids:
    # Train Set
    - '0000'
    - '0001'
    - '0002'
    - '0003'
    - '0004'
    - '0005'
    - '0006'
    - '0007'
    - '0008'
    - '0009'
    - '0010'
    - '0011'
    - '0012'
    - '0013'
    - '0014'
    - '0015'
    - '0016'
    - '0017'
    - '0018'
    - '0019'
    - '0020'
    - '0021'
    - '0022'
    - '0023'
    - '0024'
    - '0025'
    - '0026'
    - '0027'
    - '0028'
    - '0029'
    - '0030'
    - '0031'

  exception_obj_names:
    -

  outputs_dir: ${output_base_dir}
  # anno_dir: ${dataset.outputs_dir}/outputs_${match_type}/anno

network:
  detection: loftr
  detection_model_path: weight/superpoint_v1.pth

  matching: loftr
  matching_model_path: weight/superglue_outdoor.pth

sfm:
  down_ratio: 7
  gap: 3
  covis_num: 8 # -1 means all pairs
  track_length: 8

post_process:
  filter_bbox_before_filter_track_length: True
  skip_bbox_filter: True

verbose: True

# feature:
# method: 'average'
# num_leaf: 6

disable_lightning_logs: True
