# @package _global_

type: merge_anno
match_type: 'softmax'
task_name: loftr_train_geometric
split: 'train'

data_base_dir: '/cephfs-mvs/3dv-research/hexingyi/arscan_aligned/arscan_data'
sfm_dir: '/cephfs-mvs/3dv-research/hexingyi/onepose_sfm_geometric_error'
merge_output_dir: '/cephfs-mvs/3dv-research/hexingyi/onepose_merged'

names:
    # Val set
    - "0601"
    - "0602"
    - "0603"
    - "0604"
    - "0605"
    - "0606"
    - "0607"
    - "0608"
    - "0609"
    - "0610"
    - "0611"
    - "0612"
    - "0613"
    - "0614"
    - "0615"
    - "0616"
    - "0617"
    - "0618"
    - "0619"
    - "0620"
    - "0621"

network:
    detection: loftr
    matching: loftr

datamodule:
    data_dir: ${data_base_dir}
    sfm_dir: ${sfm_dir}

    out_path: ${merge_output_dir}/${task_name}/${split}.json


hydra:
    run:
        dir: ${work_dir}