# @package _global_

type: merge_anno
task_name: gats_loftr
match_type: 'softmax'
split: 'train'

data_base_dir: '/nas/users/hexingyi/arscan_data'
sfm_dir: '/nas/users/hexingyi/onepose_sfm_v2'
merge_output_dir: '/nas/users/hexingyi/onepose_merged'

names:
    # train set
    # - '0624'
    # - '0618'
    # - '0616'
    # - '0448'
    # - '0461'
    # - '0462'
    # - '0463'
    # - '0464'
    # - '0465'
    # - '0477'
    # - '0479'

# names: ${data_base_dir}
# exception_obj_names: 
#     -
# top_k_obj: null



network:
    detection: loftr
    matching: loftr

datamodule:
    data_dir: ${data_base_dir}
    sfm_dir: ${sfm_dir}

    out_path: ${merge_output_dir}/${task_name}/${split}.json


hydra:
    run:
        dir: ${work_dir}