# @package _global_

type: sfm
work_dir: ${hydra:runtime.cwd}
# data_base_dir: "data/datasets/lowtexture_test_data"
# data_base_dir: "data/arscan_data"
data_base_dir: "data/arscan_data"
output_base_dir: "data/datasets/sfm_output"

match_type: "softmax"
enable_post_refine: True

overwrite_all: True
overwrite_coarse: True
overwrite_fine: True

use_global_ray: True
use_local_ray: True

ray:
  slurm: False
  n_workers: 4
  n_cpus_per_worker: 5
  n_gpus_per_worker: 2
  local_mode: False

dataset:
  max_num_kp3d: 15000
  max_num_kp2d: 10000

  data_dir: ${data_base_dir}
  top_k_obj: null
  num_seq: 1
  ids:
    # my
    - '0603'
    
    # Test set of OnePose_LowTexture
    # - '0400'
    # - '0700'
    # - '0701'
    # - '0702'
    # - '0703'
    # - '0706'
    # - '0707'
    # - '0708'
    # - '0710'
    # - '0712'
    # - '0713'
    # - '0714'
    # - '0615'
    # - '0718'
    # - '0719'
    # - '0720'
    # - '0721'
    # - '0722'
    # - '0723'
    # - '0724'
    # - '0725'
    # - '0726'
    # - '0727'
    # - '0728'
    # - '0729'
    # - '0730'
    # - '0731'
    # - '0732'
    # - '0733'
    # - '0734'
    # - '0735'
    # - '0736'
    # - '0737'
    # - '0740'
    # - '0741'
    # - '0742'
    # - '0743'
    # - '0744'
    # - '0745'
    # - '0746'
    # - '0748'
  exception_obj_names:
    -

  outputs_dir: ${output_base_dir}

network:
  detection: loftr
  matching: loftr

sfm:
  gen_cov_from: 'pose'
  down_ratio: 5
  gap: 3
  covis_num: 10

post_optim:
  coarse_recon_data:
    feature_track_assignment_strategy: 'greedy'
  optimizer:
    solver_type: 'SecondOrder'
    residual_mode: "geometry_error"
    optimize_lr:
      depth: 0.03

post_process:
  filter_bbox_before_filter_track_length: True
  skip_bbox_filter: False

verbose: True
disable_lightning_logs: True
