# @package _global_

type: sfm
work_dir: ${hydra:runtime.cwd}
match_type: 'softmax'
redo: False

dataset:
    max_num_kp3d: 2000
    max_num_kp2d: 1000
  
    data_dir:
        - ${work_dir}/data/scan_data/023-porcelain-others obj1 obj2 obj3
  
    outputs_dir: ${work_dir}/data/sfm_model/{}
    anno_dir: ${dataset.outputs_dir}/outputs_${match_type}/anno

network:
    detection: spp_det
    detection_model_path: ${work_dir}/data/models/extractors/SuperPoint/superpoint_v1.pth

    matching: spg_match
    matching_model_path: ${work_dir}/data/models/matchers/SuperGlue/superglue_outdoor.pth

sfm:
    gap: 3
    covis_num: 8
    track_length: 8

disable_lightning_logs: True
    